api_index:
    path: /api/portal
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /api/game/portal
        permanent: true

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

swagger_ui:
    path: /api/portal/docs
    controller: api_platform.swagger.action.ui
