App\Entity\ReferralNft:
    attributes:
        refCode:
            groups: ['apiGet']
        mintHash:
            groups: ['apiGet']
        special:
            groups: ['apiGet']
        orderId:
            groups: ['apiGet']
