App\Entity\ReferralNft:
    attributes:
        refCode:
            groups: ['apiGet']
        hash:
            groups: ['apiGet']
        special:
            groups: ['apiGet']
        orderId:
            groups: ['apiGet']
