#!/usr/bin/env bash

MONGO_USER=wannabe
MONGO_PASSWORD=wannabe
MONGOBACKUPS_CONTAINER=service-creature-racer-mgob

while [[ "$#" -gt 0 ]]; do case $1 in
  -c|--create) CREATE_MODE=1;;
  -r|--restore) BACKUP_FILE_NAME="$2"; shift;;
  *) echo "Unknown parameter passed: $1"; exit 1;;
esac; shift; done

set -o pipefail

if [[ -n "$CREATE_MODE" ]]; then
  echo "Creating mongo backup...";
  if docker exec -it "${MONGOBACKUPS_CONTAINER}" curl -s -X POST http://localhost:8090/backup/creature_racer 2>&1 ; then
    echo "Database backups has been created";
    exit 0
  else
    echo "Failed to create database backup! Aborting...";
  fi
else
  if [[ -n "$BACKUP_FILE_NAME" ]]; then
    echo "Restoring mongo backup...";
    echo "Backup file: ${BACKUP_FILE_NAME}";

    if docker exec -it "${MONGOBACKUPS_CONTAINER}" mongorestore --gzip --drop --archive="/storage/creature_racer/${BACKUP_FILE_NAME}" --host=mongo:27017 --username="${MONGO_USER}" --password="${MONGO_PASSWORD}" --authenticationDatabase=admin 2>&1; then
      echo "Database backups has been restored";
      exit 0
    else
      echo "Failed to restore database backup! Aborting...";
      exit 6
    fi
  else
    echo "Backup file not provided or does not exist! Aborting...";

  fi
fi

exit 2