framework:
    cache:
        default_redis_provider: "%env(REDIS_URL)%"
        app: cache.adapter.redis
        system: cache.adapter.redis
        pools:
            index.cache:
                adapter: cache.adapter.array
            synchronization.cache:
                adapter: cache.app
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
            doctrine.system_cache_query:
                adapter: cache.adapter.array

services:
    doctrine.result_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.result_cache_pool'
    doctrine.system_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.system_cache_pool'
    doctrine.query_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.system_cache_query'