controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

admin_dashboard:
    controller: App\Controller\Admin\DashboardController::index
    path: /admin
